// <auto-generated />
using System;
using DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataLayer.Migrations
{
    [DbContext(typeof(ServicesContext))]
    [Migration("20200810144444_Debug")]
    partial class Debug
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DomainLayer.Klant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BTWNummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KlantCategorie")
                        .HasColumnType("int");

                    b.Property<string>("Naam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WoonAdres")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Klanten");
                });

            modelBuilder.Entity("DomainLayer.Limosine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EersteUurPrijs")
                        .HasColumnType("int");

                    b.Property<string>("Naam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NightLifePrijs")
                        .HasColumnType("int");

                    b.Property<int?>("WeddingPrijs")
                        .HasColumnType("int");

                    b.Property<int?>("WellnessPrijs")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Limosines");
                });

            modelBuilder.Entity("DomainLayer.Reservatie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AankomstPlaats")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Duur")
                        .HasColumnType("time");

                    b.Property<int>("KlantId")
                        .HasColumnType("int");

                    b.Property<int>("LimosineId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Startmoment")
                        .HasColumnType("datetime2");

                    b.Property<string>("VertrekPlaats")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KlantId");

                    b.HasIndex("LimosineId");

                    b.ToTable("Reservaties");
                });

            modelBuilder.Entity("DomainLayer.Reservatie", b =>
                {
                    b.HasOne("DomainLayer.Klant", "Klant")
                        .WithMany()
                        .HasForeignKey("KlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomainLayer.Limosine", "Limosine")
                        .WithMany()
                        .HasForeignKey("LimosineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
