// <auto-generated />
using System;
using DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataLayer.Migrations
{
    [DbContext(typeof(ServicesContext))]
    partial class ServicesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DomainLayer.AirportReservatie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AankomstPlaats")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KlantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Startmoment")
                        .HasColumnType("datetime2");

                    b.Property<string>("VertrekPlaats")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("limosineId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KlantId");

                    b.HasIndex("limosineId");

                    b.ToTable("AirportReservaties");
                });

            modelBuilder.Entity("DomainLayer.BusinessReservatie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AankomstPlaats")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KlantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Startmoment")
                        .HasColumnType("datetime2");

                    b.Property<string>("VertrekPlaats")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("limosineId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KlantId");

                    b.HasIndex("limosineId");

                    b.ToTable("BusinessReservatie");
                });

            modelBuilder.Entity("DomainLayer.Klant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AankomstAdres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BTWNummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankRekeningNummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KlantCategorie")
                        .HasColumnType("int");

                    b.Property<string>("Naam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OphaalAdres")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Klanten");
                });

            modelBuilder.Entity("DomainLayer.Limosine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EersteUurPrijs")
                        .HasColumnType("int");

                    b.Property<string>("Naam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NightLifePrijs")
                        .HasColumnType("int");

                    b.Property<int>("WeddingPrijs")
                        .HasColumnType("int");

                    b.Property<int>("WellnessPrijs")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Limosines");
                });

            modelBuilder.Entity("DomainLayer.NightLifeReservatie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AankomstPlaats")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KlantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Startmoment")
                        .HasColumnType("datetime2");

                    b.Property<string>("VertrekPlaats")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("limosineId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KlantId");

                    b.HasIndex("limosineId");

                    b.ToTable("NightLifeReservaties");
                });

            modelBuilder.Entity("DomainLayer.WeddingReservatie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AankomstPlaats")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KlantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Startmoment")
                        .HasColumnType("datetime2");

                    b.Property<string>("VertrekPlaats")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("limosineId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KlantId");

                    b.HasIndex("limosineId");

                    b.ToTable("WeddingReservaties");
                });

            modelBuilder.Entity("DomainLayer.WellnessReservatie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AankomstPlaats")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KlantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Startmoment")
                        .HasColumnType("datetime2");

                    b.Property<string>("VertrekPlaats")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("limosineId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KlantId");

                    b.HasIndex("limosineId");

                    b.ToTable("WellnessReservaties");
                });

            modelBuilder.Entity("DomainLayer.AirportReservatie", b =>
                {
                    b.HasOne("DomainLayer.Klant", "Klant")
                        .WithMany()
                        .HasForeignKey("KlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomainLayer.Limosine", "limosine")
                        .WithMany()
                        .HasForeignKey("limosineId");
                });

            modelBuilder.Entity("DomainLayer.BusinessReservatie", b =>
                {
                    b.HasOne("DomainLayer.Klant", "Klant")
                        .WithMany()
                        .HasForeignKey("KlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomainLayer.Limosine", "limosine")
                        .WithMany()
                        .HasForeignKey("limosineId");
                });

            modelBuilder.Entity("DomainLayer.NightLifeReservatie", b =>
                {
                    b.HasOne("DomainLayer.Klant", "Klant")
                        .WithMany()
                        .HasForeignKey("KlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomainLayer.Limosine", "limosine")
                        .WithMany()
                        .HasForeignKey("limosineId");
                });

            modelBuilder.Entity("DomainLayer.WeddingReservatie", b =>
                {
                    b.HasOne("DomainLayer.Klant", "Klant")
                        .WithMany()
                        .HasForeignKey("KlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomainLayer.Limosine", "limosine")
                        .WithMany()
                        .HasForeignKey("limosineId");
                });

            modelBuilder.Entity("DomainLayer.WellnessReservatie", b =>
                {
                    b.HasOne("DomainLayer.Klant", "Klant")
                        .WithMany()
                        .HasForeignKey("KlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomainLayer.Limosine", "limosine")
                        .WithMany()
                        .HasForeignKey("limosineId");
                });
#pragma warning restore 612, 618
        }
    }
}
